//
// Created by sooorajjj on 21/4/18.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef BLUEMOON2_SERIALPORT_H
#define BLUEMOON2_SERIALPORT_H

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_serialport_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_vst_sdk_bluemoon_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     android_serialport_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vst_sdk_bluemoon_SerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif //BLUEMOON2_SERIALPORT_H
